server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: f1234F
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
#Properties for sending email
  mail:
    host: smtp.gmail.com
    port: 465
    username: s.hawks685@gmail.com
    password: jfgwfnzqnluggojf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl.enable: true
    from-email: s.hawks685@gmail.com
logging:
  level:
    org:
      springframework:
        security: DEBUG
        mail:
          javamail: DEBUG
project:
  image : images/
app.jwtSecret: ==============================JwtSecretKey==============================
from-email: s.hawks685@gmail.com
  
#  jfgwfnzqnluggojf
