server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: f1234F
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
project:
  image : images/
app.jwtSecret: ======JwtSecretKey======

